#!/bin/bash
IFS=$'\n'
leaves=$(brew leaves)
deps=$(brew deps --union --installed --include-build --full-name ${leaves})
in_use=("${leaves[@]}" "${deps[@]}")
comm -23 <(brew list --full-name | sort) <(sort <<<"${in_use[*]}")
